---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant_namespace}
resources:
  - application.yaml
  - component.yaml
  - sa-rolebinding.yaml
  - rp.yaml
  - secrets/tenant-secrets.yaml
